### ISSUE TITLE
Game crashes when breeding ducks

### ISSUE THREAD

**Issue by PleaseAnswerMe** [Paspartout/UntitledDuckMod#28]
Version : 1.16.5
Mod version: 0.2.2
Geckolib version: 3.0.44

My game crashes when I breed two ducks together with seeds. Oh, and it made my world disappear in the singleplayer tab until I reloaded minecraft.

Crash Report:

[crash-2021-07-26_10.12.56-server.txt](https://github.com/Paspartout/UntitledDuckMod/files/6878923/crash-2021-07-26_10.12.56-server.txt)

**Comment by Paspartout** [comment]
Hm, I just tested it with the same versions of the mods and most current fabric api and it works for me.

I think it might be some other mod that is interferring here since you got a pretty big modlist.
Breeding is exactly the same as in every vanilla mob. Maybe other vanilla mobs also crash?
Could be lithium but I am not sure. Can you try to remove mods until the issue disappears, or maybe just try with lithium and see if you can reproduce the bug? My time is very limited at the moment, maybe I can take a closer look at the weekend.

**Comment by PleaseAnswerMe** [comment]
I believe the mod "notenoughbreeding" is the cause of this bug. I deleted a couple of mods and loaded back into minecraft and I couldnt reproduce the bug.
